---
title: "P6 Penultimate Analyses"
author: "Ryan Larson"
date: "`r format(Sys.time(), '%m/%d/%Y')`"
header-includes:
- \usepackage{pdflscape}
#- \usepackage{animate}
- \newcommand{\blandscape}{\begin{landscape}}
- \newcommand{\elandscape}{\end{landscape}}
output: pdf_document
fontsize: 11pt
geometry: margin=0.5in
editor_options: 
  chunk_output_type: console
---


```{r library_data, include=FALSE, message=FALSE}

library(sf)
library(tidycensus)
library(dplyr)
library(ggplot2)
library(stargazer)
library(car)
library(plm)
library(lmtest)
library(ggmap)
library(mapdata)
library(RColorBrewer)
library(gganimate)
library(fiftystater)
library(imputeTS)
library(tidycensus)
library(ggrepel)

# ***MAKE THIS A PDF OF ALL FIGURES?TABLES FOR PAPER***

#make scatterplot x = 1988 level, y = change to 2010
#first differences plot
#first differences in all variables, regress change in outcome on change in controls, save residuals, regress change in treatment on change in controls, save residuals, plot residuals against each 
#can use long difference (2010-1988) or short difference (yearly change)





#loading in data/setting working directory
#setwd("C:/Users/DELL/Documents/FE 2017") #set to google drive local folder
fe <- read.csv(file="FE_final.csv", header=T)
```

```{r, include=F, warning=F}
fe.ov <- fe %>% select(YEAR, STATENAME, STATEFIP, p6.pop, popshare.16.25, popshare.26.35, popshare.36.45,
                       popshare.46.55, popshare.56.65, popshare.66.plus, t.unemp.rate,
                       t_1.unemp.rate, t_2.unemp.rate, t_3.unemp.rate, p6.y1.notemployed.rate,
                       p6.y2.unemployed.rate, p6.y3.idle.rate, p6.y4.cfw.rate,p6.disab.rate, ssi.rate,
                       p6.marriage.rate, pctexfel, ssdi.rate, effective.wage, 
                       TANF.mu, z_labor_unemployment_compensatio,p6.degree.rate, time.indicator) %>%
                      mutate(ssi.rate=ssi.rate, norm.weight = p6.pop/(sum(p6.pop)/1550))

exfel.v <- fe %>% select(STATENAME, YEAR, pctexfel)
emp.v <- fe %>% select(STATENAME, YEAR, p6.y1.notemployed.rate)

#disability figure for aaron
fe.dis <- fe.ov %>% select(YEAR, p6.disab.rate) %>% filter(YEAR >= 1988) %>% group_by(YEAR) %>% summarise(disab = mean(p6.disab.rate, na.rm=T))

fe.dis[23,2]/fe.dis[1,2]
((fe.dis[23,2]-fe.dis[1,2])/fe.dis[1,2])*100

fe.ex <- fe.ov %>% select(YEAR, pctexfel, norm.weight) %>% filter(YEAR >= 1988) %>% group_by(YEAR) %>% 
  summarise(exfel = weighted.mean(pctexfel, w = norm.weight, na.rm=T))


```



#Descriptive Statistics


```{r,echo=F, results='asis'}
stargazer(fe.ov[fe.ov$YEAR >= 1988,c(22,15,5:10,27, 21, 11:14, 19:20, 24:26)], type="latex", style="asr", title="Unweighted Descriptive Statistics",
          summary=T, median=T, covariate.labels=c("Felony History Pct.","Not Employed Rate",
                                                  "Population Share 16-25","Population Share 26-35",
                                                  "Population Share 36-45","Population Share 46-55",
                                                  "Population Share 56-65","Population Share 66+",
                                                  "Bachelor's Degree Rate","Marriage Rate",
                                                  "Ovr. Unemployment Rate t","Ovr. Unemployment Rate t-1",
                                                  "Ovr. Unemployment Rate t-2","Ovr. Unemployment Rate t-3",
                                                  "Self-Report Disability Rate","SSI Rate",
                                                  "Effective Wage","Mean TANF Maximum",
                                                  "Unemployment Compensation"), header = F)
```


#Maps

# Felon Density Maps

```{r, include=F}
#Read in the geojson of state boundaries
#You could also use the tidycensus package: https://walkerke.github.io/tidycensus/

census_api_key("ecda17575f4d914b502c70f2bae7a5f3d253792d")

#vars <- load_variables(year = 2010, dataset = "sf1")

states <- get_decennial(geography = "state", variables = "P001001", #output = "wide",
                        geometry = T, shift_geo = T) %>% mutate(id=tolower(NAME))

  
fd <- fe %>% group_by(STATENAME) %>% summarize(density = mean(pctexfel)) %>% rename(id = STATENAME) %>% mutate( id = tolower(id))
fd.t <- fe %>% group_by(YEAR, STATENAME) %>% summarize(density = mean(pctexfel)) %>% rename(id = STATENAME) %>% mutate(id = tolower(id))

fd.1980 <- fd.t %>% filter(YEAR==1980)
fd.2010 <- fd.t %>% filter(YEAR==2010)

usa <- states %>% inner_join(fd, by = "id")
usa.1980 <- states %>% inner_join(fd.1980, by = "id")
usa.2010 <- states %>% inner_join(fd.2010, by = "id")
```

```{r, echo=F}
#average across years
ggplot(usa) +
  geom_sf(aes(geometry = geometry, fill=density)) + #geom_sf works with sf data frames
  coord_sf(crs=2163)+ #Specify crs of the projection. This is Albers equal area.
  scale_fill_distiller(palette = "Spectral",
                       breaks = c(seq(1,8,1)),
                       limits = c(1,8),
                      name = "Percent") +
  ggtitle("Figure X: Felony History Pct. in the United States: 1980-2010",
          subtitle = "Shannon et al. 2017")+
  theme(axis.text = element_blank(),
  axis.line = element_blank(),
  axis.ticks = element_blank(),
  panel.border = element_blank(),
  panel.grid = element_blank(),
  axis.title = element_blank(),
  panel.background = element_blank(),
  panel.grid.major = element_line(colour="transparent"), #Removes graticule lines
  plot.subtitle = element_text(face="italic"))
```

\pagebreak

```{r,echo=F, include=F}
#1980
ggplot(usa.1980) +
  geom_sf(aes(geometry = geometry, fill=density)) +
  coord_sf(crs=2163)+
  scale_fill_distiller(palette = "Spectral",
                       breaks = c(seq(0,13,2)),
                       limits = c(0,13),
                      name = "Percent") +
  ggtitle("Felony History Pct. in the United States: 1980",
          subtitle = "Shannon et al. 2017")+
  theme(axis.text = element_blank(),
  axis.line = element_blank(),
  axis.ticks = element_blank(),
  panel.border = element_blank(),
  panel.grid = element_blank(),
  axis.title = element_blank(),
  panel.background = element_blank(),
  panel.grid.major = element_line(colour="transparent"), #Removes graticule lines
  plot.subtitle = element_text(face="italic"))
```

\pagebreak

```{r, echo=F, include = F}
#2010
ggplot(usa.2010) +
  geom_sf(aes(geometry = geometry, fill=density)) +
  coord_sf(crs=2163)+
  scale_fill_distiller(palette = "Spectral",
                       breaks = c(seq(0,13,2)),
                       limits = c(0,13),
                      name = "Percent") +
  ggtitle("Figure 1: Felony History Pct. in the United States, 2010",
          subtitle = "Shannon et al. 2017")+
  theme(axis.text = element_blank(),
  axis.line = element_blank(),
  axis.ticks = element_blank(),
  panel.border = element_blank(),
  panel.grid = element_blank(),
  axis.title = element_blank(),
  panel.background = element_blank(),
  panel.grid.major = element_line(colour="transparent"), #Removes graticule lines
  plot.subtitle = element_text(face="italic"))

```


```{r, echo=F, fig.show='animate', eval=F}
usa.t <- states %>% inner_join(fd.t, by = "id") #fd.t being state-year dataframe

map <- ggplot(usa.t) +
  geom_sf(aes(geometry = geometry, fill=density)) + #frame = specifies animation
    coord_sf(crs=2163)+
  scale_fill_distiller(palette = "Spectral",
                       breaks = c(seq(0,13,2)),
                       limits = c(0,13),
                      name = "Percent") +
  ggtitle("Ex-Felon Density in the United States: {current_frame}",
          subtitle = "Shannon et al. 2017")+
  theme(axis.text = element_blank(),
  axis.line = element_blank(),
  axis.ticks = element_blank(),
  panel.border = element_blank(),
  panel.grid = element_blank(),
  axis.title = element_blank(),
  panel.background = element_blank(),
  plot.subtitle = element_text(face="italic"),
  panel.grid.major = element_line(colour="transparent"),
  plot.title = element_text(face="bold"))+
  transition_manual(YEAR)

animate(map, fps = 1, device = 'png')
```

#Spaghetti Plots


```{r,echo=F, results='asis'}

ggplot(emp.v, aes(x=YEAR, y = p6.y1.notemployed.rate, color = STATENAME))+
  geom_line()+
  geom_label_repel(data = subset(emp.v, YEAR==2010 & STATENAME %in% c("Minnesota", "Georgia")),
                   aes(label=STATENAME))+
  theme_minimal()+
  xlab("Year")+
  ylab("Non Employment Rate")+
  ggtitle("Non Employment Rate (18-54) by State")+
  theme(legend.position = "none") 
```

```{r,echo=F, results='asis'}

ggplot(exfel.v, aes(x=YEAR, y = pctexfel, color = STATENAME))+
  geom_line()+
  geom_label_repel(data = subset(exfel.v, YEAR==2010 & STATENAME %in% c("Minnesota", "Georgia")),
                   aes(label=STATENAME))+
  theme_minimal()+
  xlab("Year")+
  ylab("Felony History Percentage")+
  ggtitle("Estimated Felony History Pct. by State", 
          subtitle = "Shannon et. al. 2017")+
  theme(legend.position = "none") 
```

### p6 Overall Models

```{r, include=FALSE}

#weights = norm.weight redacted for now

y1.fe <- plm(p6.y1.notemployed.rate~pctexfel, data = fe.ov[fe.ov$YEAR >= 1988,], 
             index = c("STATENAME","YEAR"), effect="twoway", model="within")
y1.fe.robust <- coeftest(y1.fe, vcov=vcovHC(y1.fe,type="HC0",cluster=c("group","time")))

y1.fe.2 <- plm(p6.y1.notemployed.rate~pctexfel+popshare.26.35+popshare.36.45+popshare.46.55+popshare.56.65+popshare.66.plus+
                 p6.degree.rate+p6.marriage.rate, 
               data = fe.ov[fe.ov$YEAR >= 1988,], index = c("STATENAME","YEAR"), effect="twoway", model="within")
y1.fe.2.robust <- coeftest(y1.fe.2, vcov=vcovHC(y1.fe.2,type="HC0",cluster=c("group","time")))


y1.fe.3 <- plm(p6.y1.notemployed.rate~pctexfel+popshare.26.35+popshare.36.45+popshare.46.55+popshare.56.65+popshare.66.plus+
               p6.degree.rate+p6.marriage.rate+t.unemp.rate+t_1.unemp.rate+t_2.unemp.rate+t_3.unemp.rate, 
               data = fe.ov[fe.ov$YEAR >= 1988,], 
               index = c("STATENAME","YEAR"), effect="twoway", model="within")
y1.fe.3.robust <- coeftest(y1.fe.3, vcov=vcovHC(y1.fe.3,type="HC0",cluster=c("group","time")))


y1.fe.4 <- plm(p6.y1.notemployed.rate~pctexfel+popshare.26.35+popshare.36.45+popshare.46.55+popshare.56.65+popshare.66.plus+
                 p6.degree.rate+p6.marriage.rate+t.unemp.rate+t_1.unemp.rate+t_2.unemp.rate+t_3.unemp.rate+
                 p6.disab.rate+effective.wage+TANF.mu+z_labor_unemployment_compensatio,
                  data = fe.ov[fe.ov$YEAR >= 1988,], index = c("STATENAME","YEAR"), model="within",effect="twoway")
y1.fe.4.robust <- coeftest(y1.fe.4, vcov=vcovHC(y1.fe.4,type="HC0",cluster=c("group","time")))




y1.fe.robust.se <- list(y1.fe.robust[,2], y1.fe.2.robust[,2], y1.fe.3.robust[,2], y1.fe.4.robust[,2])
y1.fe.robust.p <- list(y1.fe.robust[,4], y1.fe.2.robust[,4], y1.fe.3.robust[,4], y1.fe.4.robust[,4])

```


```{r, results='asis', echo=F}
stargazer(y1.fe, y1.fe.2, y1.fe.3, y1.fe.4, 
          type="latex", style="aer",title="Panel Models of Not Employed Rate, 1988-2010", covariate.labels= c(
                                                  "Felony History Pct.", 
                                                  "Pop. Share 26-35",
                                                  "Pop. Share 36-45","Pop. Share 46-55",
                                                  "Pop. Share 56-65","Pop. Share 66+", 
                                                  "Degree Rate", "Marriage Rate",
                                                  "Ovr. Unemp. Rate t",
                                                  "Ovr. Unemp. Rate t-1",
                                                  "Ovr. Unemp. Rate t-2","Ovr. Unemp. Rate t-3",
                                                  "Disab. Rate",
                                                  "Effective Wage", "Mean TANF Maximum",  
                                                  "Unemployment Comp."
                                                 ),
          dep.var.caption = "Not-Employed Rate", dep.var.labels.include = FALSE,  header=F, p.auto=F, align=T,
          notes="Clustered Standard Errors by State and Year",
          se = y1.fe.robust.se, p=y1.fe.robust.p, 
          star.cutoffs = c(.05, .01, .001), star.char = c("*","**","***"),
          single.row = T, omit.stat="f", font.size="small",
          add.lines = list(c("State FE", "Yes", "Yes","Yes","Yes","Yes"), 
                           c("Year FE", "Yes", "Yes","Yes","Yes","Yes")))
```

\pagebreak

#Added-Variable Plot

```{r, results='asis'}
#model for pctexfel

y.fe <- plm(p6.y1.notemployed.rate~popshare.26.35+popshare.36.45+popshare.46.55+popshare.56.65+popshare.66.plus+
                 p6.degree.rate+p6.marriage.rate+t.unemp.rate+t_1.unemp.rate+t_2.unemp.rate+t_3.unemp.rate+
                 p6.disab.rate+effective.wage+TANF.mu+z_labor_unemployment_compensatio,
                  data = fe.ov[fe.ov$YEAR >= 1988,], index = c("STATENAME","YEAR"), model="within",effect="twoway")
x.fe <- plm(pctexfel~popshare.26.35+popshare.36.45+popshare.46.55+popshare.56.65+popshare.66.plus+
                 p6.degree.rate+p6.marriage.rate+t.unemp.rate+t_1.unemp.rate+t_2.unemp.rate+t_3.unemp.rate+
                 p6.disab.rate+effective.wage+TANF.mu+z_labor_unemployment_compensatio,
                  data = fe.ov[fe.ov$YEAR >= 1988,], index = c("STATENAME","YEAR"), model="within",effect="twoway")


#extracting fixed effects (intercepts)
y.fixed.state <- as.data.frame(as.table(fixef(y1.fe.4, effect = "individual")))
y.fixed.year <- as.data.frame(as.table(fixef(y1.fe.4, effect = "time"))) 


fe.resid <- fe.ov %>% filter(YEAR >= 1988) %>% 
  select(STATENAME, YEAR, p6.y1.notemployed.rate,pctexfel,popshare.26.35,popshare.36.45,popshare.46.55,popshare.56.65,popshare.66.plus,
                 p6.degree.rate,p6.marriage.rate,t.unemp.rate,t_1.unemp.rate,t_2.unemp.rate,t_3.unemp.rate,
                 p6.disab.rate,effective.wage,TANF.mu,z_labor_unemployment_compensatio) %>%
  mutate(YEAR = as.factor(YEAR)) %>%
  left_join(y.fixed.state, by = c("STATENAME"="Var1")) %>%
  rename(fixef.y.state = Freq) %>%
  left_join(y.fixed.year, by = c("YEAR"="Var1")) %>%
  rename(fixef.y.year = Freq) %>%
  mutate(t.response = pmodel.response(y1.fe.4), #demeaned response,
         t.predict = predict(y1.fe.4), #demeaned prediction
         y.resid.full = residuals(y1.fe.4),
         y.resid = residuals(y.fe),  #demeaned residual
         x.resid = residuals(x.fe), #demeaned residual
         y.predict.byhand = fixef.y.state+fixef.y.year+y1.fe.4$coefficients[1]*pctexfel+y1.fe.4$coefficients[2]*popshare.26.35+
           y1.fe.4$coefficients[3]*popshare.36.45+y1.fe.4$coefficients[4]*popshare.46.55+y1.fe.4$coefficients[5]*popshare.56.65+
           y1.fe.4$coefficients[6]*popshare.66.plus+y1.fe.4$coefficients[7]*p6.degree.rate+y1.fe.4$coefficients[8]*p6.marriage.rate+
           y1.fe.4$coefficients[9]*t.unemp.rate+y1.fe.4$coefficients[10]*t_1.unemp.rate+y1.fe.4$coefficients[11]*t_2.unemp.rate+
           y1.fe.4$coefficients[12]*t_3.unemp.rate+y1.fe.4$coefficients[13]*p6.disab.rate+y1.fe.4$coefficients[14]*effective.wage+
           y1.fe.4$coefficients[15]*TANF.mu+y1.fe.4$coefficients[16]*z_labor_unemployment_compensatio)


#added variable plot
ggplot(fe.resid, aes(x=x.resid, y=y.resid))+
  geom_point(shape=21, fill="green", size=2)+
  geom_smooth(method="lm",se=F, colour="red")+
  theme_bw()+
  xlab("Felony History|Controls")+
  ylab("NER|Controls")+
  ggtitle("Added-Variable Plot for Felony History")




```


\pagebreak

###Robustness Checks

```{r, include=FALSE}

y2.fe <- plm(p6.y2.unemployed.rate~pctexfel+popshare.26.35+popshare.36.45+popshare.46.55+popshare.56.65+popshare.66.plus+
                 p6.degree.rate+p6.marriage.rate+t.unemp.rate+t_1.unemp.rate+t_2.unemp.rate+t_3.unemp.rate+
                 p6.disab.rate+effective.wage+TANF.mu+z_labor_unemployment_compensatio,
                data = fe.ov[fe.ov$YEAR >= 1988,], weights = norm.weight, index = c("STATENAME","YEAR"), model="within",effect="twoway")
y2.fe.robust <- coeftest(y2.fe, vcov=vcovHC(y2.fe,type="HC0",cluster=c("group","time")))

y3.fe <- plm(p6.y3.idle.rate~pctexfel+popshare.26.35+popshare.36.45+popshare.46.55+popshare.56.65+popshare.66.plus+
                 p6.degree.rate+p6.marriage.rate+t.unemp.rate+t_1.unemp.rate+t_2.unemp.rate+t_3.unemp.rate+
                 p6.disab.rate+effective.wage+TANF.mu+z_labor_unemployment_compensatio,
                data = fe.ov[fe.ov$YEAR >= 1988,], weights = norm.weight, index = c("STATENAME","YEAR"), model="within",effect="twoway")
y3.fe.robust <- coeftest(y3.fe, vcov=vcovHC(y3.fe,type="HC0",cluster=c("group","time")))




y23.fe.robust.se <- list(y2.fe.robust[,2], y3.fe.robust[,2])
y23.fe.robust.p <- list(y2.fe.robust[,4], y3.fe.robust[,4])

```


```{r, results='asis', echo=F}
stargazer(y2.fe, y3.fe, 
          type="latex", style="aer",title="Panel Models of Unemployment and Idleness Rates, 1988-2010", covariate.labels= c(
                                                  "Felony History Pct.", 
                                                  "Pop. Share 26-35",
                                                  "Pop. Share 36-45","Pop. Share 46-55",
                                                  "Pop. Share 56-65","Pop. Share 66+", 
                                                  "Degree Rate", "Marriage Rate",
                                                  "Ovr. Unemp. Rate t",
                                                  "Ovr. Unemp. Rate t-1",
                                                  "Ovr. Unemp. Rate t-2","Ovr. Unemp. Rate t-3",
                                                  "Disab. Rate",
                                                  "Effective Wage", "Mean TANF Maximum",  
                                                  "Unemployment Comp."
                                                 ),
          dep.var.labels.include = T,  header=F, p.auto=F, align=T, dep.var.labels = c("Unemployment","Idleness"),
          notes=c("Clustered Standard Errors by State and Year.", "Weighted by State-Year total pop."),
          se = y23.fe.robust.se, p=y23.fe.robust.p, 
          star.cutoffs = c(.05, .01, .001), star.char = c("*","**","***"),
          single.row = T, omit.stat="f", font.size="small",
          add.lines = list(c("State FE", "Yes", "Yes","Yes","Yes","Yes"), 
                           c("Year FE", "Yes", "Yes","Yes","Yes","Yes")))
```

\pagebreak

#Alternative Sample Models

```{r, echo=F, include=F}
#not employed - psix men
fe.p6.m <- fe %>% select(YEAR, STATENAME, STATEFIP, p6.pop,popshare.16.25, popshare.26.35, popshare.36.45,
                       popshare.46.55, popshare.56.65, popshare.66.plus, t.unemp.rate,
                       t_1.unemp.rate, t_2.unemp.rate, t_3.unemp.rate, p6.y1.notemployed.rate.m,
                       p6.y2.unemployed.rate.m, p6.y3.idle.rate.m, p6.y4.cfw.rate.m,p6.disab.rate.m, ssi.rate,
                       p6.marriage.rate.m, pctexfel, ssdi.rate, effective.wage, 
                       TANF.mu, z_labor_unemployment_compensatio, p6.degree.rate.m,time.indicator) %>%
                      mutate(ssi.rate=ssi.rate, norm.weight = p6.pop*(1550/sum(p6.pop))) %>% rename(marriage.rate=p6.marriage.rate.m, 
                                                                                            p6.y1.notemployed.rate = p6.y1.notemployed.rate.m,
                                                                                            p6.disab.rate = p6.disab.rate.m,
                                                                                            p6.degree.rate = p6.degree.rate.m)

p6.y1.male <- plm(p6.y1.notemployed.rate~pctexfel+popshare.26.35+popshare.36.45+popshare.46.55+popshare.56.65+popshare.66.plus+
                    t.unemp.rate+t_1.unemp.rate+t_2.unemp.rate+t_3.unemp.rate+p6.degree.rate+marriage.rate+
                   p6.disab.rate+effective.wage+TANF.mu+z_labor_unemployment_compensatio,
                  data = fe.p6.m[fe.p6.m$YEAR >= 1988,], weights = norm.weight, index = c("STATENAME","YEAR"), model="within",effect="twoway")

p6.y1.male.robust <- coeftest(p6.y1.male, vcov=vcovHC(p6.y1.male,type="HC0",cluster=c("group","time")))



#not employed - psix women
fe.p6.female <- fe %>% select(YEAR, STATENAME, STATEFIP, p6.pop.female, popshare.16.25, popshare.26.35, popshare.36.45,
                       popshare.46.55, popshare.56.65, popshare.66.plus, t.unemp.rate,
                       t_1.unemp.rate, t_2.unemp.rate, t_3.unemp.rate, p6.y1.notemployed.rate.female,
                       p6.y2.unemployed.rate.female, p6.y3.idle.rate.female, p6.y4.cfw.rate.female, ssi.rate,
                       p6.marriage.rate.female, p6.disab.rate.female, pctexfel, ssdi.rate, effective.wage, 
                       TANF.mu, z_labor_unemployment_compensatio,p6.degree.rate.female,time.indicator) %>%
                      mutate(ssi.rate=ssi.rate, norm.weight = p6.pop.female*(1550/sum(p6.pop.female))) %>% 
                      rename(marriage.rate= p6.marriage.rate.female, p6.disab.rate = p6.disab.rate.female,
                             p6.y1.notemployed.rate = p6.y1.notemployed.rate.female,
                             p6.degree.rate = p6.degree.rate.female)

p6.y1.female <- plm(p6.y1.notemployed.rate~pctexfel+
                  popshare.26.35+popshare.36.45+popshare.46.55+popshare.56.65+popshare.66.plus+
                    t.unemp.rate+t_1.unemp.rate+t_2.unemp.rate+t_3.unemp.rate+p6.degree.rate+marriage.rate+
                  p6.disab.rate+effective.wage+TANF.mu+z_labor_unemployment_compensatio,
                  data = fe.p6.female[fe.p6.female$YEAR >= 1988,], weights = norm.weight, 
                  index = c("STATENAME","YEAR"), model="within",effect="twoway")
p6.y1.female.robust <- coeftest(p6.y1.female, vcov=vcovHC(p6.y1.female,type="HC0",cluster=c("group","time")))

#not employed - black psix
fe.p6.black <- fe %>% select(YEAR, STATENAME, STATEFIP, p6.pop.b, popshare.16.25, popshare.26.35, popshare.36.45,
                       popshare.46.55, popshare.56.65, popshare.66.plus, t.unemp.rate,
                       t_1.unemp.rate, t_2.unemp.rate, t_3.unemp.rate, p6.y1.notemployed.rate.b,
                       p6.y2.unemployed.rate.b, p6.y3.idle.rate.b, p6.y4.cfw.rate.b, ssi.rate,
                       p6.marriage.rate.b, p6.disab.rate.b, pctexfel.b, ssdi.rate, effective.wage, 
                       TANF.mu, z_labor_unemployment_compensatio,p6.degree.rate.b,time.indicator) %>%
                      mutate(ssi.rate=ssi.rate, norm.weight = p6.pop.b*(1550/sum(p6.pop.b, na.rm=T))) %>% rename(marriage.rate=p6.marriage.rate.b, p6.disab.rate = p6.disab.rate.b, p6.degree.rate = p6.degree.rate.b,
                    pctexfel = pctexfel.b)

#checking missings - ASEC NA's
colSums(is.na(fe.p6.black[fe.p6.black$YEAR >= 1988,]))
fe.p6.black[is.na(fe.p6.black$p6.y1.notemployed.rate.b) & fe.p6.black$YEAR >= 1988,c("YEAR","STATENAME")]
fe.p6.black[is.na(fe.p6.black$marriage.rate) & fe.p6.black$YEAR >= 1988,c("YEAR","STATENAME")]
dim(fe.p6.black[is.na(fe.p6.black$p6.disab.rate) & fe.p6.black$YEAR >= 1988,c("YEAR","STATENAME")])

#imputation - just disability for now
fe.p6.black <- fe.p6.black %>% mutate(dis.imputed = ifelse(YEAR >= 1988, ifelse(is.na(p6.disab.rate), "Imputed","Not Imputed"), NA), 
                                      p6.disab.rate = ifelse(YEAR >= 1988, na.interpolation(p6.disab.rate, option = "linear"), NA),
                                      mar.imputed = ifelse(YEAR >= 1988, ifelse(is.na(marriage.rate), "Imputed","Not Imputed"), NA), 
                                      marriage.rate = ifelse(YEAR >= 1988, na.interpolation(marriage.rate, option = "linear"), NA)) 
  

p6.y1.black <- plm(p6.y1.notemployed.rate.b~pctexfel+popshare.26.35+popshare.36.45+popshare.46.55+popshare.56.65+popshare.66.plus+
                    t.unemp.rate+t_1.unemp.rate+t_2.unemp.rate+t_3.unemp.rate+p6.degree.rate+marriage.rate+
                    p6.disab.rate+effective.wage+TANF.mu+z_labor_unemployment_compensatio+
                    as.factor(dis.imputed)+as.factor(mar.imputed),
                  data = fe.p6.black[fe.p6.black$YEAR >= 1988,], weight = norm.weight,
                  index = c("STATENAME","YEAR"), model="within",effect="twoway")
p6.y1.black.robust <- coeftest(p6.y1.black, vcov=vcovHC(p6.y1.black,type="HC0",cluster=c("group","time")))

#not employed - white psix
fe.p6.white <- fe %>% select(YEAR, STATENAME, STATEFIP, p6.pop.w,popshare.16.25, popshare.26.35, popshare.36.45,
                       popshare.46.55, popshare.56.65, popshare.66.plus, t.unemp.rate,
                       t_1.unemp.rate, t_2.unemp.rate, t_3.unemp.rate, p6.y1.notemployed.rate.w,
                       p6.y2.unemployed.rate.w, p6.y3.idle.rate.w, p6.y4.cfw.rate.w, ssi.rate,
                       p6.marriage.rate.w, p6.disab.rate.w, pctexfel, ssdi.rate, effective.wage, 
                       TANF.mu, z_labor_unemployment_compensatio,p6.degree.rate.w, time.indicator) %>%
                      mutate(ssi.rate=ssi.rate, norm.weight = p6.pop.w*(1550/sum(p6.pop.w)), marriage.rate=p6.marriage.rate.w,
                             p6.disab.rate = p6.disab.rate.w, p6.degree.rate = p6.degree.rate.w)

p6.y1.white <- plm(p6.y1.notemployed.rate.w~pctexfel+popshare.26.35+popshare.36.45+popshare.46.55+popshare.56.65+popshare.66.plus+
                  t.unemp.rate+t_1.unemp.rate+t_2.unemp.rate+t_3.unemp.rate+p6.degree.rate+marriage.rate+
                  p6.disab.rate+effective.wage+TANF.mu+z_labor_unemployment_compensatio,
                  data = fe.p6.white[fe.p6.white$YEAR >= 1988,], weights = norm.weight, index = c("STATENAME","YEAR"), model="within",effect="twoway")
p6.y1.white.robust <- coeftest(p6.y1.white, vcov=vcovHC(p6.y1.white,type="HC0",cluster=c("group","time")))





alt.y1.fe.robust.se <- list(p6.y1.male.robust[,2], p6.y1.female.robust[,2], p6.y1.black.robust[,2], p6.y1.white.robust[,2])
alt.y1.fe.robust.p <- list(p6.y1.male.robust[,4], p6.y1.female.robust[,4], p6.y1.black.robust[,4], p6.y1.white.robust[,4])
```

```{r, results='asis', echo=F}
stargazer(p6.y1.male, p6.y1.female, p6.y1.black, p6.y1.white,
          type="latex", style="aer", title="Alternative Sample Models" , covariate.labels= c(
                                                  "Felony History Pct.", 
                                                  "Pop. Share 26-35",
                                                  "Pop. Share 36-45","Pop. Share 46-55",
                                                  "Pop. Share 56-65","Pop. Share 66+", 
                                                  "Degree Rate", "Marriage Rate",
                                                  "Ovr. Unemp. Rate t",
                                                  "Ovr. Unemp. Rate t-1",
                                                  "Ovr. Unemp. Rate t-2","Ovr. Unemp. Rate t-3",
                                                  "Disab. Rate",
                                                  "Effective Wage", "Mean TANF Maximum",  "Unemployment Comp.",
                                                  "Disab. Imputed",
                                                  "Marriage Imputed"),
          dep.var.labels.include = FALSE,
          column.labels = c("Male","Female","Black","White"), header=F, p.auto=F, align = T,
          notes=c("Clustered Standard Errors by State and Year.", "Weighted by State-Year total pop."),
          se = alt.y1.fe.robust.se, p=alt.y1.fe.robust.p, 
          star.cutoffs = c(.05, .01, .001), star.char = c("*","**","***"),
          single.row = T, omit.stat="f", font.size="small",
          add.lines = list(c("State FE", "Yes", "Yes","Yes","Yes"), 
                           c("Year FE", "Yes", "Yes","Yes","Yes")))
```

\pagebreak







\pagebreak

# Alternative Specifications of Disabiility

```{r, warning=F, include=F}


y1.fe.d <- plm(p6.y1.notemployed.rate~pctexfel+popshare.26.35+popshare.36.45+popshare.46.55+popshare.56.65+popshare.66.plus+
                  t.unemp.rate+t_1.unemp.rate+t_2.unemp.rate+t_3.unemp.rate+p6.degree.rate+p6.marriage.rate+
                  p6.disab.rate+ssi.rate+effective.wage+TANF.mu+z_labor_unemployment_compensatio,
                  data = fe.ov, weights = norm.weight, index = c("STATENAME","YEAR"), model="within",effect="twoway")
y1.fe.robust.d <- coeftest(y1.fe.d, vcov=vcovHC(y1.fe.d,type="HC0",cluster=c("group","time")))

fe.ov.missfill <- fe.ov %>% mutate(p6.disab.rate = ifelse(is.na(p6.disab.rate), 0, p6.disab.rate))

y2.fe.d <- plm(p6.y1.notemployed.rate~pctexfel+popshare.26.35+popshare.36.45+popshare.46.55+popshare.56.65+popshare.66.plus+
                  t.unemp.rate+t_1.unemp.rate+t_2.unemp.rate+t_3.unemp.rate+p6.degree.rate+p6.marriage.rate+
                  p6.disab.rate+ssi.rate+effective.wage+TANF.mu+z_labor_unemployment_compensatio,
                  data = fe.ov.missfill, weights = norm.weight, index = c("STATENAME","YEAR"), model="within",effect="twoway")
y2.fe.robust.d <- coeftest(y2.fe.d, vcov=vcovHC(y2.fe.d,type="HC0",cluster=c("group","time")))

y3.fe.d <- plm(p6.y1.notemployed.rate~pctexfel+popshare.26.35+popshare.36.45+popshare.46.55+popshare.56.65+popshare.66.plus+
                 t.unemp.rate+t_1.unemp.rate+t_2.unemp.rate+t_3.unemp.rate+
                   p6.disab.rate+p6.marriage.rate+effective.wage+TANF.mu+z_labor_unemployment_compensatio+p6.degree.rate,
                  data = fe.ov.missfill, weights = norm.weight, index = c("STATENAME","YEAR"), model="within",effect="twoway")
y3.fe.robust.d <- coeftest(y3.fe.d, vcov=vcovHC(y3.fe.d,type="HC0",cluster=c("group","time")))





d.fe.robust.se <- list(y1.fe.robust.d[,2], y2.fe.robust.d[,2], y3.fe.robust.d[,2])
d.fe.robust.p <- list(y1.fe.robust.d[,4], y2.fe.robust.d[,4], y3.fe.robust.d[,4])

```


```{r, results='asis', echo=F}
stargazer(y1.fe.d, y2.fe.d, y3.fe.d,
          type="latex", style="aer", title="Alternative Specifications of Disability", covariate.labels= c(
                                                  "Felon History Pct.", 
                                                  "Pop. Share 26-35",
                                                  "Pop. Share 36-45","Pop. Share 46-55",
                                                  "Pop. Share 56-65","Pop. Share 66+", 
                                                  "Degree Rate", "Marriage Rate",
                                                  "Ovr. Unemp. Rate t",
                                                  "Ovr. Unemp. Rate t-1",
                                                  "Ovr. Unemp. Rate t-2","Ovr. Unemp. Rate t-3",
                                                  "Disab.rate","SSI Rate", 
                                                  "Effective Wage", "Mean TANF Maximum",  
                                                  "Unemployment Comp."
                                                  ),
          dep.var.labels.include = FALSE,
          dep.var.caption = "",
          column.labels =  c("with SSI","Imputed","Imputed no SSI"),
          header=F, p.auto=F,
          notes=c("Clustered Standard Errors by State and Year.", "Weighted by State-Year total pop."), 
          se = d.fe.robust.se, p=d.fe.robust.p, 
          star.cutoffs = c(.05, .01, .001), star.char = c("*","**","***"),
          single.row = T, omit.stat="f", font.size="small",
          add.lines = list(c("State FE", "Yes", "Yes","Yes","Yes"), 
                           c("Year FE", "Yes", "Yes","Yes","Yes")))
```

\pagebreak



# Appendix



```{r, include=F}
corr<-round(cor(fe.ov[fe.ov$YEAR >= 1988,c(22,15,5:10,27, 21, 11:14, 19:20, 24:26)], use="pairwise.complete.obs", method="pearson" ),2)
corr[upper.tri(corr)] <-""
upper <- as.matrix(corr)
rownames(upper) <- c("Felony History Pct.","Not Employed Rate",
                                                  "Population Share 16-25","Population Share 26-35",
                                                  "Population Share 36-45","Population Share 46-55",
                                                  "Population Share 56-65","Population Share 66+",
                                                  "Bachelor's Degree Rate","Marriage Rate",
                                                  "Ovr. Unemployment Rate t","Ovr. Unemployment Rate t-1",
                                                  "Ovr. Unemployment Rate t-2","Ovr. Unemployment Rate t-3",
                                                  "Self-Report Disability Rate","SSI Rate",
                                                  "Effective Wage","Mean TANF Maximum",
                                                  "Unemployment Compensation")

corr2<-round(cor(fe.ov[fe.ov$YEAR >= 1988,c(15:18,22)], use="pairwise.complete.obs", method="pearson" ),2)
corr2[upper.tri(corr2)] <-""
upper2 <- as.matrix(corr2)
rownames(upper2) <- c("Not Employed Rate","Unemployment Rate", "Idleness Rate", "Can't Find Work Rate","Felony History Pct.")
```


```{r, results='asis', echo=F}
stargazer(upper, header=F, title="Pairwise Correlations", font.size="small", column.sep.width = "0.15pt",
          single.row=TRUE,covariate.labels=c(as.character(paste(c("Variable",1:20)))))

#stargazer(upper2, header=F, title="Pairwise Correlations", font.size="small", column.sep.width = "0.15pt",
 #         single.row=TRUE,covariate.labels=c(as.character(paste(c("Variable",1:20)))))
```

